DROP DATABASE IF EXISTS boozeclues_db;
CREATE DATABASE boozeclues_db;

CREATE TABLE users(
  id INT NOT NULL AUTO_INCREMENT,
  pic VARCHAR(80) NULL,
  email VARCHAR(40) NOT NULL,
  pass VARCHAR(20) NOT  NULL,
  game_id VARCHAR(500) NULL,
  corr_ans INT(5) DEFAULT 0,
  game_vics INT(4) DEFAULT 0,
  access BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE games(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  active BOOLEAN DEFAULT true,
  PRIMARY KEY (id)
);

CREATE TABLE teams(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  users VARCHAR(30) NOT NULL,
  game_id INT(3) NOT NULL,
  score INT (4) DEFAULT 0,
  PRIMARY KEY (id)
);

SELECT * FROM users;
SELECT * FROM games;
SELECT * FROM teams;
